# Generated by Django 3.2.7 on 2021-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='neighborhood',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
